### ISSUE TITLE
Adding of Azure china appinsights  to the listener so that we can link it up with that

### ISSUE THREAD

**Issue by venkatkriish** [adrianmo/jmeter-backend-azure#21]
Hi Team,
We are trying to use azure china appinsights for the jmeter backend listeners to have a dashboard to appinsights.

we are facing issue that it cannot reached out the appinsights even though we have given the correct instrumentation key

Can we have a enhansement for this to work on this issue i found a nice document over here from microsoft

https://docs.microsoft.com/en-us/dotnet/api/microsoft.applicationinsights.extensibility.telemetryconfiguration.-ctor?view=azure-dotnet#Microsoft_ApplicationInsights_Extensibility_TelemetryConfiguration__ctor_System_String_Microsoft_ApplicationInsights_Channel_ITelemetryChannel_

Thanks,
Venkatesh.K

**Comment by adrianmo** [comment]
Hi @venkatkriish,

Thanks for your feedback!  I believe you are not getting any data into your App Insights because the endpoint configuration is not targeting Azure China. I haven't thought about it before, but it makes sense that you should be allowed to override the default App Insights endpoint and target Azure China or Azure Government.

I'll work on a fix for this and create a PR with the changes. I'll ask you to try out the JAR file to validate the changes because I don't have access to either Azure China or Azure Gov. 

Thank you!

**Comment by adrianmo** [comment]
@venkatkriish I've published a pre-released that would want you to test. 

Download the JAR for version 0.2.6-rc0 from here: https://github.com/adrianmo/jmeter-backend-azure/releases/tag/0.2.6-rc0

Then instead of using the "instrumentationKey" in the plugin configuration table, use "connectionString" with the value of your App Insights connection string. It can be found in the overview tab, below the instrumentation key.

![image](https://user-images.githubusercontent.com/3786750/122950563-d5b8de00-d37c-11eb-9c9e-6447c5af3030.png)

Please let me know if it works. If it does, I'll publish a new version of the plugin.

**Comment by venkatkriish** [comment]
Hi Team,

Thanks for the above enhancement we are testing it out with the above release jar file.
i will let you know once we have done with the testing 
This was really appreciate with your enhancement.

Thanks.

**Comment by venkatkriish** [comment]
Closing this issue as w are able to get the metrics in azure china as well.

**Comment by adrianmo** [comment]
Thanks for testing this - 0.2.6 is now released and available from Maven Central 🚀
